---
# yamllint disable rule:line-length

- name: Delete IBM Cloud VPC VSI
  hosts: localhost
  connection: local

  tasks:
    - name: get floating ip id
      ibm.cloudcollection.ibm_is_floating_ip_info:
        name: "{{ name_prefix }}-fip"
      register: floating_ip
      ignore_errors: yes

    - name: release floating ip
      ibm.cloudcollection.ibm_is_floating_ip:
        id: "{{ floating_ip.resource.id }}"
        state: absent
      ignore_errors: yes

    - name: get vsi id
      ibm.cloudcollection.ibm_is_instance_info:
         name: "{{ name_prefix }}"
      register: instance

    - name: destroy a vm
      ibm.cloudcollection.ibm_is_instance:
         id: "{{ instance.resource.id }}"
         state: absent
         keys: []

