---
# yamllint disable rule:line-length

- name: Delete IBM Cloud VPC VSI
  hosts: localhost
  connection: local

  tasks:
    - name: include tasks needed to remove VM
      include_tasks:
        remove_vm_ibm_tasks.yml
      ibm.cloudcollection.ibm_is_floating_ip_info:
        name: "{{ server_name }}-fip"
      register: floating_ip
      ignore_errors: true

    - name: release floating ip
      ibm.cloudcollection.ibm_is_floating_ip:
        id: "{{ floating_ip.resource.id }}"
        state: absent
      ignore_errors: true

    - name: get vsi id
      ibm.cloudcollection.ibm_is_instance_info:
        name: "{{ server_name }}"
      register: instance

    - name: destroy a vm
      ibm.cloudcollection.ibm_is_instance:
        id: "{{ instance.resource.id }}"
        state: absent
        keys: []
