---
# yamllint disable rule:line-length

- hosts: "{{ satellite_bootstrap_fqdn | default('satellite.lab.sohlberg.io') }}"
  connection: local
  vars:
    organization: 'satellite_inventory'
    node_group: 'foreman_delete_us'

  tasks:

    - name: Include all secret credentials
      no_log: true
      include_vars: secrets.yml

    - name: Remove all hosts in inventory group "{{ node_group }}" from Satellite org "{{ organization }}"
      redhat.satellite.host:
        name: "{{ item }}"
        state: absent
        validate_certs: false
        username: "{{ satellite_bootstrap_username }}"
        password: "{{ satellite_bootstrap_password }}"
        server_url: "https://{{ satellite_bootstrap_fqdn }}"
      with_items: "{{ groups[node_group] }}"
      register: remove_hosts_result

    - debug:
        var: remove_hosts_result
